//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMeteroWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JustLessons\\fishtext.lml")]
        public string LoadedLessonFile {
            get {
                return ((string)(this["LoadedLessonFile"]));
            }
            set {
                this["LoadedLessonFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestCourse")]
        public string LoadedCourseFile {
            get {
                return ((string)(this["LoadedCourseFile"]));
            }
            set {
                this["LoadedCourseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CourseLessonNumber {
            get {
                return ((int)(this["CourseLessonNumber"]));
            }
            set {
                this["CourseLessonNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KeyboardLayouts\\Dvorak.lml")]
        public string KeyboardLayoutFile {
            get {
                return ((string)(this["KeyboardLayoutFile"]));
            }
            set {
                this["KeyboardLayoutFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New")]
        public string LessonLettersFont {
            get {
                return ((string)(this["LessonLettersFont"]));
            }
            set {
                this["LessonLettersFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New")]
        public string KeyboardFont {
            get {
                return ((string)(this["KeyboardFont"]));
            }
            set {
                this["KeyboardFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FontContext {
            get {
                return ((string)(this["FontContext"]));
            }
            set {
                this["FontContext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCourseOpened {
            get {
                return ((bool)(this["IsCourseOpened"]));
            }
            set {
                this["IsCourseOpened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CourseName {
            get {
                return ((string)(this["CourseName"]));
            }
            set {
                this["CourseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public string LessonLettersFontSize {
            get {
                return ((string)(this["LessonLettersFontSize"]));
            }
            set {
                this["LessonLettersFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string MainFontColor {
            get {
                return ((string)(this["MainFontColor"]));
            }
            set {
                this["MainFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#646464")]
        public string RaidedFontColor {
            get {
                return ((string)(this["RaidedFontColor"]));
            }
            set {
                this["RaidedFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bahnschrift")]
        public string SummaryFont {
            get {
                return ((string)(this["SummaryFont"]));
            }
            set {
                this["SummaryFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#282828")]
        public string MainBackground {
            get {
                return ((string)(this["MainBackground"]));
            }
            set {
                this["MainBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#222222")]
        public string SecondBackground {
            get {
                return ((string)(this["SecondBackground"]));
            }
            set {
                this["SecondBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#1A1A1A")]
        public string ThirdBackground {
            get {
                return ((string)(this["ThirdBackground"]));
            }
            set {
                this["ThirdBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#202020")]
        public string ThirdSecBackground {
            get {
                return ((string)(this["ThirdSecBackground"]));
            }
            set {
                this["ThirdSecBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string SummaryFontColor {
            get {
                return ((string)(this["SummaryFontColor"]));
            }
            set {
                this["SummaryFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#2A2A2A")]
        public string KeyboardBackgroundColor {
            get {
                return ((string)(this["KeyboardBackgroundColor"]));
            }
            set {
                this["KeyboardBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string KeyboardFontColor {
            get {
                return ((string)(this["KeyboardFontColor"]));
            }
            set {
                this["KeyboardFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#202020")]
        public string KeyboardBorderColor {
            get {
                return ((string)(this["KeyboardBorderColor"]));
            }
            set {
                this["KeyboardBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#80F6FF")]
        public string KeyboardHighlightColor {
            get {
                return ((string)(this["KeyboardHighlightColor"]));
            }
            set {
                this["KeyboardHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string LessonName {
            get {
                return ((string)(this["LessonName"]));
            }
            set {
                this["LessonName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingTime {
            get {
                return ((int)(this["TypingTime"]));
            }
            set {
                this["TypingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingLength {
            get {
                return ((int)(this["TypingLength"]));
            }
            set {
                this["TypingLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingErrors {
            get {
                return ((int)(this["TypingErrors"]));
            }
            set {
                this["TypingErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml")]
        public string ThemeResourceDictionary {
            get {
                return ((string)(this["ThemeResourceDictionary"]));
            }
            set {
                this["ThemeResourceDictionary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://application:,,,/MahApps.Metro;component/Styles/Accents/steel.xaml")]
        public string ColorSchemeResourceDictionary {
            get {
                return ((string)(this["ColorSchemeResourceDictionary"]));
            }
            set {
                this["ColorSchemeResourceDictionary"] = value;
            }
        }
    }
}
