//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMeteroWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JustLessons\\fishtext.lml")]
        public string LoadedLessonFile {
            get {
                return ((string)(this["LoadedLessonFile"]));
            }
            set {
                this["LoadedLessonFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoadedCourseFile {
            get {
                return ((string)(this["LoadedCourseFile"]));
            }
            set {
                this["LoadedCourseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CourseLessonNumber {
            get {
                return ((int)(this["CourseLessonNumber"]));
            }
            set {
                this["CourseLessonNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KeyboardLayouts\\Dvorak.lml")]
        public string KeyboardLayoutFile {
            get {
                return ((string)(this["KeyboardLayoutFile"]));
            }
            set {
                this["KeyboardLayoutFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string LessonLettersFont {
            get {
                return ((string)(this["LessonLettersFont"]));
            }
            set {
                this["LessonLettersFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string KeyboardFont {
            get {
                return ((string)(this["KeyboardFont"]));
            }
            set {
                this["KeyboardFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FontContext {
            get {
                return ((string)(this["FontContext"]));
            }
            set {
                this["FontContext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCourseOpened {
            get {
                return ((bool)(this["IsCourseOpened"]));
            }
            set {
                this["IsCourseOpened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CourseName {
            get {
                return ((string)(this["CourseName"]));
            }
            set {
                this["CourseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public string LessonLettersFontSize {
            get {
                return ((string)(this["LessonLettersFontSize"]));
            }
            set {
                this["LessonLettersFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string MainFontColor {
            get {
                return ((string)(this["MainFontColor"]));
            }
            set {
                this["MainFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#AA004884")]
        public string RaidedFontColor {
            get {
                return ((string)(this["RaidedFontColor"]));
            }
            set {
                this["RaidedFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI Semibold")]
        public string SummaryFont {
            get {
                return ((string)(this["SummaryFont"]));
            }
            set {
                this["SummaryFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF1E1E1E")]
        public string MainBackground {
            get {
                return ((string)(this["MainBackground"]));
            }
            set {
                this["MainBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF121212")]
        public string SecondBackground {
            get {
                return ((string)(this["SecondBackground"]));
            }
            set {
                this["SecondBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF191919")]
        public string ThirdBackground {
            get {
                return ((string)(this["ThirdBackground"]));
            }
            set {
                this["ThirdBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF121212")]
        public string ThirdSecBackground {
            get {
                return ((string)(this["ThirdSecBackground"]));
            }
            set {
                this["ThirdSecBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD1FEFF")]
        public string SummaryFontColor {
            get {
                return ((string)(this["SummaryFontColor"]));
            }
            set {
                this["SummaryFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#66262626")]
        public string KeyboardBackgroundColor {
            get {
                return ((string)(this["KeyboardBackgroundColor"]));
            }
            set {
                this["KeyboardBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDBDBDB")]
        public string KeyboardFontColor {
            get {
                return ((string)(this["KeyboardFontColor"]));
            }
            set {
                this["KeyboardFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF191919")]
        public string KeyboardBorderColor {
            get {
                return ((string)(this["KeyboardBorderColor"]));
            }
            set {
                this["KeyboardBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF17C4F5")]
        public string KeyboardHighlightColor {
            get {
                return ((string)(this["KeyboardHighlightColor"]));
            }
            set {
                this["KeyboardHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string LessonName {
            get {
                return ((string)(this["LessonName"]));
            }
            set {
                this["LessonName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingTime {
            get {
                return ((int)(this["TypingTime"]));
            }
            set {
                this["TypingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingLength {
            get {
                return ((int)(this["TypingLength"]));
            }
            set {
                this["TypingLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypingErrors {
            get {
                return ((int)(this["TypingErrors"]));
            }
            set {
                this["TypingErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml")]
        public string ThemeResourceDictionary {
            get {
                return ((string)(this["ThemeResourceDictionary"]));
            }
            set {
                this["ThemeResourceDictionary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://application:,,,/MahApps.Metro;component/Styles/Accents/steel.xaml")]
        public string ColorSchemeResourceDictionary {
            get {
                return ((string)(this["ColorSchemeResourceDictionary"]));
            }
            set {
                this["ColorSchemeResourceDictionary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RequireWPM {
            get {
                return ((bool)(this["RequireWPM"]));
            }
            set {
                this["RequireWPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStatistics {
            get {
                return ((bool)(this["ShowStatistics"]));
            }
            set {
                this["ShowStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string KeyboardErrorHighlightColor {
            get {
                return ((string)(this["KeyboardErrorHighlightColor"]));
            }
            set {
                this["KeyboardErrorHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NecessaryCPM {
            get {
                return ((int)(this["NecessaryCPM"]));
            }
            set {
                this["NecessaryCPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int MaxAcceptableMistakes {
            get {
                return ((int)(this["MaxAcceptableMistakes"]));
            }
            set {
                this["MaxAcceptableMistakes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF7D7D7D")]
        public string HandsColor {
            get {
                return ((string)(this["HandsColor"]));
            }
            set {
                this["HandsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public string HandsOpacity {
            get {
                return ((string)(this["HandsOpacity"]));
            }
            set {
                this["HandsOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string HandsThickness {
            get {
                return ((string)(this["HandsThickness"]));
            }
            set {
                this["HandsThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHands {
            get {
                return ((bool)(this["ShowHands"]));
            }
            set {
                this["ShowHands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItTypingTest {
            get {
                return ((bool)(this["ItTypingTest"]));
            }
            set {
                this["ItTypingTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsOpenUnderCourse {
            get {
                return ((bool)(this["IsOpenUnderCourse"]));
            }
            set {
                this["IsOpenUnderCourse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty")]
        public string LessonInCourseFileName {
            get {
                return ((string)(this["LessonInCourseFileName"]));
            }
            set {
                this["LessonInCourseFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousLoadedLesson {
            get {
                return ((string)(this["PreviousLoadedLesson"]));
            }
            set {
                this["PreviousLoadedLesson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsBackgroundImage {
            get {
                return ((bool)(this["IsBackgroundImage"]));
            }
            set {
                this["IsBackgroundImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultData\\Background.jpg")]
        public string BackgroundImagePath {
            get {
                return ((string)(this["BackgroundImagePath"]));
            }
            set {
                this["BackgroundImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JustLessons\\Typing tests\\topWords_EN.lml")]
        public string TestWordListPath {
            get {
                return ((string)(this["TestWordListPath"]));
            }
            set {
                this["TestWordListPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int TestWordCount {
            get {
                return ((int)(this["TestWordCount"]));
            }
            set {
                this["TestWordCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string MenuOpacity {
            get {
                return ((string)(this["MenuOpacity"]));
            }
            set {
                this["MenuOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string KeyboardOpacity {
            get {
                return ((string)(this["KeyboardOpacity"]));
            }
            set {
                this["KeyboardOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double MaxTapperingAuraSize {
            get {
                return ((double)(this["MaxTapperingAuraSize"]));
            }
            set {
                this["MaxTapperingAuraSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double MinTapperingAuraSize {
            get {
                return ((double)(this["MinTapperingAuraSize"]));
            }
            set {
                this["MinTapperingAuraSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double TapperingMilliseconds {
            get {
                return ((double)(this["TapperingMilliseconds"]));
            }
            set {
                this["TapperingMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Cases\\Press game maps\\Test map")]
        public string LoadedMapFolder {
            get {
                return ((string)(this["LoadedMapFolder"]));
            }
            set {
                this["LoadedMapFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double MusicVolume {
            get {
                return ((double)(this["MusicVolume"]));
            }
            set {
                this["MusicVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("824522754971402241")]
        public string DiscordID {
            get {
                return ((string)(this["DiscordID"]));
            }
            set {
                this["DiscordID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFirstTextInputOpen {
            get {
                return ((bool)(this["IsFirstTextInputOpen"]));
            }
            set {
                this["IsFirstTextInputOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SingleLineWithStaticCaret")]
        public string TextInputType {
            get {
                return ((string)(this["TextInputType"]));
            }
            set {
                this["TextInputType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("typeSound.wav")]
        public string TapClickSoundFile {
            get {
                return ((string)(this["TapClickSoundFile"]));
            }
            set {
                this["TapClickSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("errorSound.wav")]
        public string ErrorClickSoundFile {
            get {
                return ((string)(this["ErrorClickSoundFile"]));
            }
            set {
                this["ErrorClickSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BackgroundBlurRadius {
            get {
                return ((string)(this["BackgroundBlurRadius"]));
            }
            set {
                this["BackgroundBlurRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableParallax {
            get {
                return ((bool)(this["EnableParallax"]));
            }
            set {
                this["EnableParallax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KeyboardLayouts\\Redactor.lml")]
        public string SecondKeyboardLayoutFile {
            get {
                return ((string)(this["SecondKeyboardLayoutFile"]));
            }
            set {
                this["SecondKeyboardLayoutFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CurrentLayout {
            get {
                return ((int)(this["CurrentLayout"]));
            }
            set {
                this["CurrentLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDictionary {
            get {
                return ((bool)(this["IsDictionary"]));
            }
            set {
                this["IsDictionary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RecentCourses.json")]
        public string RecentCourcesPath {
            get {
                return ((string)(this["RecentCourcesPath"]));
            }
            set {
                this["RecentCourcesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RecentLayouts.json")]
        public string RecentLayoutsPath {
            get {
                return ((string)(this["RecentLayoutsPath"]));
            }
            set {
                this["RecentLayoutsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RecentSkins.json")]
        public string RecentConfigs {
            get {
                return ((string)(this["RecentConfigs"]));
            }
            set {
                this["RecentConfigs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TypingSpeedStats.json")]
        public string AllTypingSpeedPath {
            get {
                return ((string)(this["AllTypingSpeedPath"]));
            }
            set {
                this["AllTypingSpeedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CoursesStats.json")]
        public string CourcesStatisticsPath {
            get {
                return ((string)(this["CourcesStatisticsPath"]));
            }
            set {
                this["CourcesStatisticsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RecentTests.json")]
        public string RecentTestDictionariesPath {
            get {
                return ((string)(this["RecentTestDictionariesPath"]));
            }
            set {
                this["RecentTestDictionariesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShakeBackgroundInTyping {
            get {
                return ((bool)(this["ShakeBackgroundInTyping"]));
            }
            set {
                this["ShakeBackgroundInTyping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShakeBackgroundInClicking {
            get {
                return ((bool)(this["ShakeBackgroundInClicking"]));
            }
            set {
                this["ShakeBackgroundInClicking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideImageWhenLessonStart {
            get {
                return ((bool)(this["HideImageWhenLessonStart"]));
            }
            set {
                this["HideImageWhenLessonStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlurUpImageWhenLessonStart {
            get {
                return ((bool)(this["BlurUpImageWhenLessonStart"]));
            }
            set {
                this["BlurUpImageWhenLessonStart"] = value;
            }
        }
    }
}
