//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMeteroWindow.Resources.localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFMeteroWindow.Resources.localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во симв.
        /// </summary>
        public static string uCharactersCount {
            get {
                return ResourceManager.GetString("uCharactersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите урок, с которого желаете начать.
        /// </summary>
        public static string uChooseTheBeginLesson {
            get {
                return ResourceManager.GetString("uChooseTheBeginLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на симв/мин.
        /// </summary>
        public static string uCPM {
            get {
                return ResourceManager.GetString("uCPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на симв/сек.
        /// </summary>
        public static string uCPS {
            get {
                return ResourceManager.GetString("uCPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тёмная.
        /// </summary>
        public static string uDark {
            get {
                return ResourceManager.GetString("uDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введить путь к папке с курсом.
        /// </summary>
        public static string uEnterCourseFolder {
            get {
                return ResourceManager.GetString("uEnterCourseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название шрифта.
        /// </summary>
        public static string uEnterFontFamily {
            get {
                return ResourceManager.GetString("uEnterFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите команду.
        /// </summary>
        public static string uEnterTheCommand {
            get {
                return ResourceManager.GetString("uEnterTheCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введить путь к раскладке.
        /// </summary>
        public static string uEnterThePathToKeyboardLayout {
            get {
                return ResourceManager.GetString("uEnterThePathToKeyboardLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провал!.
        /// </summary>
        public static string uFail {
            get {
                return ResourceManager.GetString("uFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проводник.
        /// </summary>
        public static string uFileExplorer {
            get {
                return ResourceManager.GetString("uFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на указательным на .
        /// </summary>
        public static string uIndex {
            get {
                return ResourceManager.GetString("uIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершён.
        /// </summary>
        public static string uIsFinished {
            get {
                return ResourceManager.GetString("uIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Левым .
        /// </summary>
        public static string uLeft {
            get {
                return ResourceManager.GetString("uLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая.
        /// </summary>
        public static string uLight {
            get {
                return ResourceManager.GetString("uLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить текущий курс.
        /// </summary>
        public static string uMenuEditCurrentCourse {
            get {
                return ResourceManager.GetString("uMenuEditCurrentCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить текущий урок.
        /// </summary>
        public static string uMenuEditCurrentLesson {
            get {
                return ResourceManager.GetString("uMenuEditCurrentLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор.
        /// </summary>
        public static string uMenuEditor {
            get {
                return ResourceManager.GetString("uMenuEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уроки.
        /// </summary>
        public static string uMenuLessons {
            get {
                return ResourceManager.GetString("uMenuLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый курс.
        /// </summary>
        public static string uMenuNewCourse {
            get {
                return ResourceManager.GetString("uMenuNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый урок.
        /// </summary>
        public static string uMenuNewLesson {
            get {
                return ResourceManager.GetString("uMenuNewLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть следующий урок.
        /// </summary>
        public static string uMenuNextLesson {
            get {
                return ResourceManager.GetString("uMenuNextLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть новый курс.
        /// </summary>
        public static string uMenuOpenNewCourse {
            get {
                return ResourceManager.GetString("uMenuOpenNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть новый урок.
        /// </summary>
        public static string uMenuOpenNewLesson {
            get {
                return ResourceManager.GetString("uMenuOpenNewLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть предыдущий урок.
        /// </summary>
        public static string uMenuPrevLesson {
            get {
                return ResourceManager.GetString("uMenuPrevLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string uMenuQuit {
            get {
                return ResourceManager.GetString("uMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string uMenuSettings {
            get {
                return ResourceManager.GetString("uMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на средним на .
        /// </summary>
        public static string uMiddle {
            get {
                return ResourceManager.GetString("uMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя скорость.
        /// </summary>
        public static string uMiddleSpeed {
            get {
                return ResourceManager.GetString("uMiddleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибок.
        /// </summary>
        public static string uMistakes {
            get {
                return ResourceManager.GetString("uMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string uNo {
            get {
                return ResourceManager.GetString("uNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мизинцем на .
        /// </summary>
        public static string uPinky {
            get {
                return ResourceManager.GetString("uPinky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правым .
        /// </summary>
        public static string uRight {
            get {
                return ResourceManager.GetString("uRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на безымянным на .
        /// </summary>
        public static string uRing {
            get {
                return ResourceManager.GetString("uRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные цвета.
        /// </summary>
        public static string uSettBaseColors {
            get {
                return ResourceManager.GetString("uSettBaseColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шрифты.
        /// </summary>
        public static string uSettFonts {
            get {
                return ResourceManager.GetString("uSettFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string uSettHeader {
            get {
                return ResourceManager.GetString("uSettHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет границы клавиш.
        /// </summary>
        public static string uSettKbBorderColor {
            get {
                return ResourceManager.GetString("uSettKbBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет клавиш.
        /// </summary>
        public static string uSettKbButtonsColor {
            get {
                return ResourceManager.GetString("uSettKbButtonsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет ошибочно нажатых клавиш.
        /// </summary>
        public static string uSettKbErrorHighlightColor {
            get {
                return ResourceManager.GetString("uSettKbErrorHighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шрифт символов.
        /// </summary>
        public static string uSettKbFontFamily {
            get {
                return ResourceManager.GetString("uSettKbFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет выделения клавиш.
        /// </summary>
        public static string uSettKbHighlightColor {
            get {
                return ResourceManager.GetString("uSettKbHighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл раскладки.
        /// </summary>
        public static string uSettKbLayoutFile {
            get {
                return ResourceManager.GetString("uSettKbLayoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет символов.
        /// </summary>
        public static string uSettKbTextColor {
            get {
                return ResourceManager.GetString("uSettKbTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиатура.
        /// </summary>
        public static string uSettKeyboard {
            get {
                return ResourceManager.GetString("uSettKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шрифт символов урока.
        /// </summary>
        public static string uSettLessonLettersFont {
            get {
                return ResourceManager.GetString("uSettLessonLettersFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер шрифта символов урока.
        /// </summary>
        public static string uSettLessonLettonFontSize {
            get {
                return ResourceManager.GetString("uSettLessonLettonFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уроки и курсы.
        /// </summary>
        public static string uSettLessonsAndCourses {
            get {
                return ResourceManager.GetString("uSettLessonsAndCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет символов урока.
        /// </summary>
        public static string uSettLessonSymbolsColor {
            get {
                return ResourceManager.GetString("uSettLessonSymbolsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основной цвет (фон).
        /// </summary>
        public static string uSettMainColor {
            get {
                return ResourceManager.GetString("uSettMainColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет успешно введённых символов урока.
        /// </summary>
        public static string uSettRaidedLessonSymbolsColor {
            get {
                return ResourceManager.GetString("uSettRaidedLessonSymbolsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требовать выполнение упражнений с заданной скоростью.
        /// </summary>
        public static string uSettRequireWPM {
            get {
                return ResourceManager.GetString("uSettRequireWPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вторичный цвет (меню).
        /// </summary>
        public static string uSettSecondColor {
            get {
                return ResourceManager.GetString("uSettSecondColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет вторичных меню.
        /// </summary>
        public static string uSettSecondMenuColor {
            get {
                return ResourceManager.GetString("uSettSecondMenuColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать статистику во время прохождения урока.
        /// </summary>
        public static string uSettShowStatistics {
            get {
                return ResourceManager.GetString("uSettShowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет текстовых полей.
        /// </summary>
        public static string uSettTextBoxColor {
            get {
                return ResourceManager.GetString("uSettTextBoxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шрифт текста интерфейса.
        /// </summary>
        public static string uSettUItext {
            get {
                return ResourceManager.GetString("uSettUItext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет текста интерфейса.
        /// </summary>
        public static string uSettUItextColor {
            get {
                return ResourceManager.GetString("uSettUItextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет окна.
        /// </summary>
        public static string uSettWindowColor {
            get {
                return ResourceManager.GetString("uSettWindowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Пробел&quot;.
        /// </summary>
        public static string uSpace {
            get {
                return ResourceManager.GetString("uSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость на каждой секунде.
        /// </summary>
        public static string uSpeedInEverySecond {
            get {
                return ResourceManager.GetString("uSpeedInEverySecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех!.
        /// </summary>
        public static string uSuccess {
            get {
                return ResourceManager.GetString("uSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Урок.
        /// </summary>
        public static string uTheLesson {
            get {
                return ResourceManager.GetString("uTheLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема.
        /// </summary>
        public static string uTheme {
            get {
                return ResourceManager.GetString("uTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на большим на .
        /// </summary>
        public static string uThumb {
            get {
                return ResourceManager.GetString("uThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string uTime {
            get {
                return ResourceManager.GetString("uTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string uYes {
            get {
                return ResourceManager.GetString("uYes", resourceCulture);
            }
        }
    }
}
