//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMeteroWindow.Resources.localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFMeteroWindow.Resources.localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на указательным на .
        /// </summary>
        public static string uIndex {
            get {
                return ResourceManager.GetString("uIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Левым .
        /// </summary>
        public static string uLeft {
            get {
                return ResourceManager.GetString("uLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить текущий курс.
        /// </summary>
        public static string uMenuEditCurrentCourse {
            get {
                return ResourceManager.GetString("uMenuEditCurrentCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить текущий урок.
        /// </summary>
        public static string uMenuEditCurrentLesson {
            get {
                return ResourceManager.GetString("uMenuEditCurrentLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор.
        /// </summary>
        public static string uMenuEditor {
            get {
                return ResourceManager.GetString("uMenuEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уроки.
        /// </summary>
        public static string uMenuLessons {
            get {
                return ResourceManager.GetString("uMenuLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый курс.
        /// </summary>
        public static string uMenuNewCourse {
            get {
                return ResourceManager.GetString("uMenuNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый урок.
        /// </summary>
        public static string uMenuNewLesson {
            get {
                return ResourceManager.GetString("uMenuNewLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть следующий урок.
        /// </summary>
        public static string uMenuNextLesson {
            get {
                return ResourceManager.GetString("uMenuNextLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть новый курс.
        /// </summary>
        public static string uMenuOpenNewCourse {
            get {
                return ResourceManager.GetString("uMenuOpenNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть новый урок.
        /// </summary>
        public static string uMenuOpenNewLesson {
            get {
                return ResourceManager.GetString("uMenuOpenNewLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть предыдущий урок.
        /// </summary>
        public static string uMenuPrevLesson {
            get {
                return ResourceManager.GetString("uMenuPrevLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string uMenuQuit {
            get {
                return ResourceManager.GetString("uMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string uMenuSettings {
            get {
                return ResourceManager.GetString("uMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на средним на .
        /// </summary>
        public static string uMiddle {
            get {
                return ResourceManager.GetString("uMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мизинцем на .
        /// </summary>
        public static string uPinky {
            get {
                return ResourceManager.GetString("uPinky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правым .
        /// </summary>
        public static string uRight {
            get {
                return ResourceManager.GetString("uRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на безымянным на .
        /// </summary>
        public static string uRing {
            get {
                return ResourceManager.GetString("uRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные цвета.
        /// </summary>
        public static string uSettBaseColors {
            get {
                return ResourceManager.GetString("uSettBaseColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string uSettHeader {
            get {
                return ResourceManager.GetString("uSettHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основной цвет (фон).
        /// </summary>
        public static string uSettMainColor {
            get {
                return ResourceManager.GetString("uSettMainColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вторичный цвет (меню).
        /// </summary>
        public static string uSettSecondColor {
            get {
                return ResourceManager.GetString("uSettSecondColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет вторичных меню.
        /// </summary>
        public static string uSettSecondMenuColor {
            get {
                return ResourceManager.GetString("uSettSecondMenuColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет текстовых полей.
        /// </summary>
        public static string uSettTextBoxColor {
            get {
                return ResourceManager.GetString("uSettTextBoxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет окна.
        /// </summary>
        public static string uSettWindowColor {
            get {
                return ResourceManager.GetString("uSettWindowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Пробел&quot;.
        /// </summary>
        public static string uSpace {
            get {
                return ResourceManager.GetString("uSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на большим на .
        /// </summary>
        public static string uThumb {
            get {
                return ResourceManager.GetString("uThumb", resourceCulture);
            }
        }
    }
}
